// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function MakeNewSpell(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MakeNewSpell'](arg1, arg2, arg3, arg4);
}

export function SaveNewSpell(arg1) {
  return window['go']['main']['App']['SaveNewSpell'](arg1);
}
